# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginreg_app', '0002_auto_20170628_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
